### ISSUE TITLE
FoF/Subfind header of SIMBA 1P simulations do not contain the right cosmology.  

### ISSUE THREAD

**Issue by benopp99** [franciscovillaescusa/CAMELS#14]
The header of the FoF/Subfind SIMBA 1P files contains the wrong cosmology when it varies.

For example in the 1P_0 simulation (IllustrisTNG/1P_0/fof_subhalo_tab_033.hdf5) should have Omega0=0.1, but in this header file it is Omega0=0.3.  

Checking the SIMBA LH simulations, this does not seem to be a problem.  And this is not a problem with the SIMBA snapshot files.  But the 1P_0 to 1P_10 (or 1P_1_n5 to 1P_1_5) where Omega0 is varied, this appears to be an issue.

**Comment by franciscovillaescusa** [comment]
Thanks for this. I believe this has been sorted out.
