### ISSUE TITLE
Duplicate entries in TNG-1P set?

### ISSUE THREAD

**Issue by krittisharma** [franciscovillaescusa/CAMELS#24]
CAMELS documentation says that the [1P set for IllustrisTNG](https://camels.readthedocs.io/en/latest/suites_sets.html?highlight=1p) is constructed by doing 4 variations of each of the 28 parameters, thus giving 28*4+1 simulations where 1 extra is for the fiducial setting. However, the [IllustrisTNG/CosmoAstroSeed_IllustrisTNG_L25n256_1P.txt ](https://github.com/franciscovillaescusa/CAMELS/blob/3a53eafc60954d4736b50c4f08403970e3ef5c55/docs/params/IllustrisTNG/CosmoAstroSeed_IllustrisTNG_L25n256_1P.txt) has 140 simulations and many of them are duplicate entries - for example 1P_p1_n2 and 1P_p8_n2 have duplicate entries in this file. Is there any difference between these?

**Comment by franciscovillaescusa** [comment]
Please indicate the duplicate rows. 1P_p1_n2 and 1P_p8_n2 have different values of Omega0 and h (Hubble function).
The only entries that are duplicated are those with 1P_pX_0, as those represent the fiducial model that is always the same
